### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by akshayag** [rfeinman/AdversarialDetection#4]
I am trying to generate the adversarial images on SVHN database but getting following execution error. Can you please help or it would be helpful if you can provide me the adversarial images from SVHN database (if possible)
Traceback (most recent call last):
  File "train_model.py", line 5, in <module>
    from detect.util import get_data, get_model
  File "/home/iiitd/caffe/python/detect.py", line 24, in <module>
    import caffe
  File "/home/iiitd/caffe/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, RMSPropSolver, AdaDeltaSolver, AdamSolver, NCCL, Timer
  File "/home/iiitd/caffe/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver, NesterovSolver, AdaGradSolver, \
ImportError: dynamic module does not define module export function (PyInit__caffe)

**Comment by rfeinman** [comment]
Hi @akshayag,

It appears that you have a conflicting package name in your $PYTHONPATH. Can you remove caffe from your $PYTHONPATH env variable so that when the script imports from "detect" it uses the correct package? My code has a package named "detect."
